apiVersion: apps/v1
kind: Deployment
metadata:
  name: soularr
  labels:
    app.kubernetes.io/name: soularr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: soularr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: soularr
    spec:
      volumes:
       - name: nfs-vol 
         nfs:
           server: 192.168.0.99
           path: /mnt/test1/media/Music
       - name: config
         nfs:
           server: 192.168.0.99
           path: /mnt/test1/media/config/soularr/
      containers:
        - name: soularr
          image: mrusse08/soularr:latest
          livenessProbe:
            httpGet:
              path: / 
              port: 8989
            initialDelaySeconds: 21600
            failureThreshold: 6
            periodSeconds: 10
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: SCRIPT_INTERVAL
              value: "300"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: config 
              mountPath: /data
            - name: nfs-vol 
              mountPath: /media
  
