apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app.kubernetes.io/name: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flaresolverr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          livenessProbe:
            httpGet:
              path: /
              port: 8191
            initialDelaySeconds: 60
            failureThreshold: 6
            periodSeconds: 10
          env:
            - name: LOG_LEVEL
              value: info
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Etc/UTC"
    
