apiVersion: v1
kind: Service
metadata:
  name: svc-flaresolverr
spec:
  selector:
    app.kubernetes.io/name: flaresolverr
  ports:
    - name: webui
      protocol: TCP 
      port: 80
      targetPort: 8191 


