apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      volumes:
       - name: nfs-vol 
         nfs:
           server: 192.168.0.99
           path: /mnt/test1/media/
       - name: config
         nfs:
           server: 192.168.0.99
           path: /mnt/test1/media/
      containers:
        - name: radarr
          image: ghcr.io/hotio/radarr:latest
          livenessProbe: 
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 60
            failureThreshold: 6
            periodSeconds: 10
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: config 
              mountPath: /config
            - name: nfs-vol 
              mountPath: /media
    
