apiVersion: v1
kind: Pod
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
spec:
  volumes:
   - name: nfs-vol 
     nfs:
       server: 192.168.0.114
       path: /mnt/test1/media/
   - name: config
     persistentVolumeClaim:
       claimName: config-radarr
  containers:
    - name: radarr
      image: ghcr.io/hotio/radarr:latest
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "002"
        - name: TZ
          value: "Etc/UTC"
      ports:
        - containerPort: 7878
      volumeMounts:
        - name: config 
          mountPath: /config
        - name: nfs-vol 
          mountPath: /media

