apiVersion: apps/v1
kind: Deployment 
metadata:
  name: qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
    spec:
      volumes:
       - name: nfs-vol 
         nfs:
           server: 192.168.0.114
           path: /mnt/test1/media/
       - name: config
         persistentVolumeClaim:
           claimName: config-qbittorrent
      containers:
        - name: qbittorrent
          image: ghcr.io/hotio/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Etc/UTC"
            - name: WEBUI_PORTS
              value: "8080/tcp,8080/udp"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config 
              mountPath: /config
            - name: nfs-vol 
              mountPath: /media
    
