apiVersion: v1
kind: Service
metadata:
  name: svc-qbittorrent
spec:
  selector:
    app.kubernetes.io/name: qbittorrent
  ports:
    - name: webui
      protocol: TCP 
      port: 80
      targetPort: 8080


