apiVersion: v1
kind: Service
metadata:
  name: svc-readarr
spec:
  selector:
    app.kubernetes.io/name: readarr
  ports:
    - name: webui
      protocol: TCP 
      port: 80
      targetPort: 8787


