apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      volumes:
       - name: config
         nfs:
           path: /mnt/test1/media/config/prowlarr
           server: 192.168.0.99
      containers:
        - name: prowlarr
          image: ghcr.io/hotio/prowlarr:latest
          livenessProbe:
            httpGet:
              path: /ping
              port: 9696
            initialDelaySeconds: 60
            failureThreshold: 6
            periodSeconds: 3
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: config 
              mountPath: /config
    
