apiVersion: v1
kind: Pod
metadata:
  name: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  volumes:
   - name: config
     persistentVolumeClaim:
       claimName: config-prowlarr
  containers:
    - name: prowlarr
      image: ghcr.io/hotio/prowlarr:latest
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "002"
        - name: TZ
          value: "Etc/UTC"
      ports:
        - containerPort: 9696
      volumeMounts:
        - name: config 
          mountPath: /config

