apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  labels:
    app.kubernetes.io/name: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lidarr
    spec:
      volumes:
       - name: nfs-vol 
         nfs:
           server: 192.168.0.99
           path: /mnt/test1/media/
       - name: config
         nfs:
           server: 192.168.0.99
           path: /mnt/test1/media/config/lidarr
      containers:
        - name: lidarr
          livenessProbe:
            httpGet:
              path: /ping
              port: 8686
            initialDelaySeconds: 60
            failureThreshold: 6
            periodSeconds: 10
          image: ghcr.io/hotio/lidarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 8686
          volumeMounts:
            - name: config 
              mountPath: /config
            - name: nfs-vol 
              mountPath: /media
    
