apiVersion: v1
kind: Pod
metadata:
  name: lidarr
  labels:
    app.kubernetes.io/name: lidarr
spec:
  volumes:
   - name: nfs-vol 
     nfs:
       server: 192.168.0.114
       path: /mnt/test1/media/
   - name: config
     persistentVolumeClaim:
       claimName: config-lidarr
  containers:
    - name: lidarr
      image: ghcr.io/hotio/lidarr:latest
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "002"
        - name: TZ
          value: "Etc/UTC"
      ports:
        - containerPort: 8686
      volumeMounts:
        - name: config 
          mountPath: /config
        - name: nfs-vol 
          mountPath: /media

